master:
  build: .
  environment:
#    JAVA_OPTS: "-Djava.awt.headless=true"
    JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
    JENKINS_USER: "admin"
    JENKINS_PASS: "admin"
  ports:
    - "50000:50000"
    - "2124:8080"
  volumes:
    - /var/jenkins_home